# Dasar-dasar Operasi Tensor
## Mengimpor library pytorch

Tensor adalah struktur data multidimensional yang digunakan dalam komputasi numerik dan pemrosesan data, terutama dalam machine learning, deep learning, dan pengolahan citra. Tensor adalah generalisasi dari skalar (0 dimensi), vektor (1 dimensi), matriks (2 dimensi), dan dapat memiliki lebih banyak dimensi. Dalam konteks machine learning, tensor adalah bentuk dasar untuk menyimpan dan mengoperasikan data.

Beberapa karakteristik tensor adalah sebagai berikut:

1. **Dimensi**: Tensor dapat memiliki nol dimensi (skalar), satu dimensi (vektor), dua dimensi (matriks), atau lebih dari dua dimensi (tensor berderajat tinggi). Sebagai contoh, tensor 3D adalah tensor dengan tiga dimensi.

2. **Elemen**: Setiap elemen di dalam tensor dapat memiliki nilai numerik. Di dalam tensor, elemen-elemen ini diindeks oleh indeks-indeks yang sesuai dengan dimensi tensor tersebut.

3. **Tipe Data**: Tensor dapat memiliki tipe data yang berbeda, seperti bilangan bulat (integer), bilangan riil (floating-point), atau tipe data lainnya, tergantung pada aplikasi dan kebutuhan.

4. **Operasi**: Anda dapat melakukan berbagai operasi matematis pada tensor, seperti penjumlahan, perkalian, pemotongan, atau perhitungan gradien.

5. **Contoh**: Beberapa contoh tensor dalam konteks machine learning adalah:
   - Skalar: Tensor 0D (contoh: angka tunggal).
   - Vektor: Tensor 1D (contoh: vektor fitur dalam data).
   - Matriks: Tensor 2D (contoh: matriks bobot dalam jaringan neural).
   - Tensor berderajat tinggi: Tensor dengan tiga atau lebih dimensi (contoh: citra berwarna dengan tiga dimensi: tinggi, lebar, dan warna).

Dalam praktiknya, kerangka kerja deep learning seperti TensorFlow, PyTorch, atau Keras memiliki dukungan built-in untuk manipulasi tensor. Ini memungkinkan pengembang dan peneliti untuk melakukan operasi tensor dengan mudah, yang sangat penting dalam pelatihan model deep learning dan analisis data. Tensors memainkan peran sentral dalam perhitungan yang melibatkan jumlah besar data dan komputasi paralel yang diperlukan dalam machine learning modern.

In [ ]:
!pip3 install https://download.pytorch.org/whl/cu80/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
!pip3 install torchvision

In [2]:
import torch

## Membuat variabel baru bertipe tensor

In [3]:
# membuat variabel kosong dengan ukuran 2,4
emptyvar = torch.empty(2, 4)
# membuat variabel random dengan ukuran 2,3,4
randomvar = torch.rand(2, 3, 4)
# membuat variabel tensor dengan nilai 1 berukuran 2,3,4
onesvar = torch.ones(2, 3, 4)
# membuat variabel tensor dengan nilai 0 berukuran 4,5
zerosvar = torch.zeros(4, 5)
# membuat variabel tensor yang berurutan sejumlah n atau dari x hingga y (bahkan dengan step atau jarak tertentu)
rentang = torch.arange(12, dtype=torch.float32)
rentang2 = torch.arange(0, 12, 2, dtype=torch.float32)

# silahkan coba cetak satu-per-satu dari variabel diatas
print(emptyvar, randomvar, onesvar, zerosvar, rentang, rentang2)


tensor([[-3.5888e+15,  4.5873e-41, -3.6003e+15,  4.5873e-41],
        [-3.6065e+15,  4.5873e-41, -3.6005e+15,  4.5873e-41]]) tensor([[[0.6324, 0.9448, 0.5101, 0.3945],
         [0.3912, 0.9594, 0.4523, 0.2351],
         [0.6781, 0.8439, 0.9636, 0.6499]],

        [[0.0505, 0.2560, 0.4796, 0.0750],
         [0.4014, 0.3069, 0.2683, 0.4965],
         [0.6214, 0.7721, 0.5639, 0.2169]]]) tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]) tensor([ 0.,  2.,  4.,  6.,  8., 10.])


## Membuat variabel tensor dengan tipe data spesifik

In [4]:
# membuat tensor dengan tipe data integer
intvar = torch.ones(2, 2, dtype=torch.int)
# membuat tensor dengan tipe data float
floatvar = torch.rand(2, 2, dtype=torch.float)

print(intvar, floatvar)
print(intvar.dtype, floatvar.dtype)
print(intvar.size(), floatvar.size())

tensor([[1, 1],
        [1, 1]], dtype=torch.int32) tensor([[0.8645, 0.7013],
        [0.7046, 0.5958]])
torch.int32 torch.float32
torch.Size([2, 2]) torch.Size([2, 2])


## Operasi Aritmatika Dasar pada Tensor

In [5]:
# mengisi tensor dengan nilai
var_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
# operasi aritmatika pada tensor
var_b = torch.tensor([[1, 2, 3], [4, 5, 6]])
var_c = var_a + var_b
print(var_c)

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


## Cara Lain Operasi Penjumlahan

In [6]:
# cara lain
var_c = torch.add(var_a, var_b) # hasil penjumlahan var_a dan var_b disimpan di objek BARU dengan nama variabel var_c
print(var_c)

# cara lain pada variabel yang sama (in-place operation)
var_a.add_(var_b)
print(var_a)

# --- lebih lanjut mengenai in-place opeartion dalam pyTorch dalam diskusi : https://discuss.pytorch.org/t/what-is-in-place-operation/16244

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


## Operasi Aritmatika lainnya

In [7]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

# --- dot-product dalam pyToch 
z_kali = x * y
z_kali_2 = torch.mul(x, y)
# perhatikan bedanya dengan torch.mm(x, y) <- ini perkalian matriks dan 
# torch.matmul(x, y) <- ini perkalian matriks juga tapi perintah ini support broadcasting 
# (https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics)
# ---

z_bagi = x / y
z_bagi_2 = torch.div(x, y)

z_pengurangan = x - y
z_pengurangan_2 = torch.sub(x, y)

z_pangkat = x ** y
z_pangkat_2 = torch.pow(x, y)

## Manipulasi Matriks

In [8]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0])  # mencetak hanya kolom pertama
print(x[0, :])  # mencetak hanya baris pertama
print(x[1, 1])  # mencetak nilai pada baris ke-1 dan kolom ke-1
print(x[1, 1].item())  # mencetak hanya nilai (tanpa identitas jenis tensor)

tensor([[0.3410, 0.5389, 0.4280],
        [0.7656, 0.9371, 0.9629],
        [0.6862, 0.4582, 0.7153],
        [0.4435, 0.6778, 0.6659],
        [0.2020, 0.2017, 0.0818]])
tensor([0.3410, 0.7656, 0.6862, 0.4435, 0.2020])
tensor([0.3410, 0.5389, 0.4280])
tensor(0.9371)
0.9371301531791687


## Reshaping Matriks
Mengubah matriks 2 dimensi menjadi array 1 dimensi

In [9]:
x = torch.rand(4, 4)
print(x)
print(x.shape)
y = x.view(16)
print(y)
print(y.shape)

tensor([[0.8567, 0.3160, 0.0040, 0.0812],
        [0.8044, 0.5758, 0.3986, 0.1689],
        [0.3867, 0.6969, 0.3465, 0.9028],
        [0.5293, 0.3452, 0.6293, 0.9383]])
torch.Size([4, 4])
tensor([0.8567, 0.3160, 0.0040, 0.0812, 0.8044, 0.5758, 0.3986, 0.1689, 0.3867,
        0.6969, 0.3465, 0.9028, 0.5293, 0.3452, 0.6293, 0.9383])
torch.Size([16])


Cara lain untuk mentransformasikan matriks

In [10]:
y = x.view(-1, 8) 
print(y)
print(y.shape)
# --- nilai -1 pada fungsi `view`` menandakan dimensi pertama otomatis mengikuti bentuk tensor awal, 
# dalam hal ini karena data ada 4*4 = 16 elemen, maka dimensi pertama menjadi 16/8 = 2

tensor([[0.8567, 0.3160, 0.0040, 0.0812, 0.8044, 0.5758, 0.3986, 0.1689],
        [0.3867, 0.6969, 0.3465, 0.9028, 0.5293, 0.3452, 0.6293, 0.9383]])
torch.Size([2, 8])


In [11]:
# misalnya kita memiliki sebuah matriks berukuran (3,4,5)
x = torch.rand(3, 4, 5)
print(x)

# maka kita akan coba reshape matriks tersebut menjadi (12,5)
x_new = x.reshape(12, -1)
'''
artinya: jadikan 2 baris dengan mengurangi 1 dimensi
juga dapat dilakukan dengan menggunakan
x_new = x.view(12, -1)
'''
print(x_new)

tensor([[[0.2117, 0.4284, 0.0303, 0.3762, 0.2135],
         [0.5930, 0.5386, 0.3158, 0.3734, 0.5564],
         [0.6518, 0.9398, 0.8103, 0.4788, 0.6255],
         [0.6314, 0.3160, 0.4396, 0.6057, 0.1325]],

        [[0.2477, 0.7658, 0.8143, 0.9298, 0.5090],
         [0.2781, 0.4150, 0.1292, 0.0389, 0.0305],
         [0.6713, 0.6764, 0.2910, 0.0893, 0.4494],
         [0.2838, 0.7012, 0.4809, 0.5496, 0.0063]],

        [[0.1398, 0.9766, 0.4067, 0.7719, 0.9682],
         [0.7420, 0.2588, 0.3061, 0.4877, 0.2343],
         [0.6502, 0.0071, 0.0340, 0.4807, 0.4223],
         [0.7337, 0.0394, 0.5334, 0.4179, 0.6388]]])
tensor([[0.2117, 0.4284, 0.0303, 0.3762, 0.2135],
        [0.5930, 0.5386, 0.3158, 0.3734, 0.5564],
        [0.6518, 0.9398, 0.8103, 0.4788, 0.6255],
        [0.6314, 0.3160, 0.4396, 0.6057, 0.1325],
        [0.2477, 0.7658, 0.8143, 0.9298, 0.5090],
        [0.2781, 0.4150, 0.1292, 0.0389, 0.0305],
        [0.6713, 0.6764, 0.2910, 0.0893, 0.4494],
        [0.2838, 0.7012, 0.4809,

Sebaliknya, kita juga dapat membuat matriks dari array 1 dimensi

In [12]:
x = torch.arange(6, 100, 3, dtype=torch.float32)
print(x)
print(x.size())

x_new = x.reshape(4,8)
print(x_new)

# perlu diingat bahwa target reshape harus sama dengan jumlah elemen yang ada pada tensor awal

tensor([ 6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39., 42., 45.,
        48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78., 81., 84., 87.,
        90., 93., 96., 99.])
torch.Size([32])
tensor([[ 6.,  9., 12., 15., 18., 21., 24., 27.],
        [30., 33., 36., 39., 42., 45., 48., 51.],
        [54., 57., 60., 63., 66., 69., 72., 75.],
        [78., 81., 84., 87., 90., 93., 96., 99.]])


## Konversi dari Numpy ke Tensor

In [13]:
import numpy as np

a = torch.ones(5)
print(a)
# memberikan referensi ke variabel b, 
# gunakan a.numpy().copy() untuk membuat data baru dengan nilai yang sama dengan variabel a
b = a.numpy() 
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


Perlu diperhatikan bahwa mengkonversi dari numpy ke tensor tidak membuat kopi, melainkan mengubah referensi dari numpy ke tensor.
Nilai b akan berubah ketika kita melakukan modifikasi terhadap nilai a.

In [14]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [15]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a = a + 1
print(a)
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


# Operasi Menggunakan GPU

In [16]:
if torch.cuda.is_available():
    # Mengatur nama device sebagai variabel
    device = torch.device("cuda")
    # Membuat variabel tensor yang menggunakan device
    x = torch.ones(5, device=device)

    # Memindahkan variable yang sudah dibuat sebelumnya ke device
    y = torch.ones(5)
    y = y.to(device)

    # Memindahkan kembali ke CPU
    x = x.to("cpu")

# Mengaktifkan Variabel dengan Autograd

In [17]:
x = torch.ones(2, 2, requires_grad=True) # memungkinkan pytorch untuk menghitung gradient secara otomatis
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
